---

- name: Add the Dropbox package signing key to apt
  apt_key:
    keyserver: pgp.mit.edu
    id: 5044912E
  sudo: true

- name: Add the Dropbox repository
  apt_repository:
    repo: "deb http://linux.dropbox.com/{{ ansible_distribution.lower() }} {{ ansible_distribution_release }} main"
    state: present
  sudo: true

- name: Add the Spotify package signing key to apt
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 94558F59
  sudo: true

- name: Add the spotify repository
  apt_repository:
    repo: "deb http://repository.spotify.com testing non-free"
    state: present
  sudo: true

- name: Remove all of the unnecessary packages that come with Debian and Ubuntu
  apt:
    pkg: "{{ item }}"
    state: absent
  sudo: true
  with_items:

    # Games
    - aisleriot
    - four-in-a-row
    - gnome-chess
    - gnome-games
    - gnome-klotski
    - gnome-mahjongg
    - gnome-mines
    - gnome-nibbles
    - gnome-robots
    - gnome-sudoku
    - gnome-tetravex
    - hitori
    - iagno
    - lightsoff
    - quadrapassel
    - swell-foop
    - tali
    - xboard

    # Utilities
    - bluez
    - ppp
    - gnome-orca
    - gnome-accessibility-themes
    - vino
    - espeak-data
    - libespeak1
    - icedove
    - thunderbird
    - totem
    - totem-common
    - totem-plugins
    - rhythmbox

- name: Install useful graphical software
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - dia
    - dropbox
    - gimp
    - keepassx
    - rxvt-unicode-256color
    - transmission-gtk

    # Commandline software, still useful
    - mpd
    - ncmpcpp
  sudo: true

- name: Install Firefox (Ubuntu)
  apt:
    pkg: firefox
    state: installed
  sudo: true
  when: ansible_distribution == 'Ubuntu'

- name: Add the Mozilla Debian Team's apt repo GPG key (Debian)
  apt:
    pkg: pkg-mozilla-archive-keyring
    state: installed
  when: ansible_distribution == 'Debian'
  sudo: true

- name: Install Mozilla Debian Team's backports repo
  apt_repository:
    repo: deb http://mozilla.debian.net/ jessie-backports iceweasel-release
    state: present
  when: ansible_distribution == 'Debian'
  sudo: true

- name: Install latest version of Iceweasel (Debian)
  apt:
    pkg: iceweasel
    state: latest
  when: ansible_distribution == 'Debian'
  sudo: true

- name: Install the latest version of Spotify (Debian)
  apt:
    pkg: spotify-client
    state: installed
  when: ansible_distribution == 'Debian'
  sudo: true
