---
# .travis.yml for ansible. Based on
# https://servercheck.in/blog/testing-ansible-roles-travis-ci-github

language: python
python: 2.7

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

before_script:
  # Generate an ansible hosts file. Check the groups in bootstrap.yml and add localhost to each.
  - cd mfoo/ansible-playbooks && grep 'hosts' bootstrap.yml | sed 's/.*: \(.*$\)/\1/g' | sort -u | sed "s/\(.*\)/\[\1\]\rlocalhost/g" > inventory


script:
  # Check syntax
  - ansible-playbook -i inventory bootstrap.yml --syntax-check

  # Check playbook execution
  - ansible-playbook -i inventory bootstrap.yml --connection=local --sudo

  # Check playbook idempotence
  - >
    ansible-playbook -i inventory bootstrap.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
