---

- name: Install essential packages
  apt:
    pkg: "{{ item }}"
    state: present
  sudo: true
  with_items:
    - build-essential
    - cmake
    - exuberant-ctags
    - git
    - subversion
    - mercurial
    #- kdiff3
    - meld
    - gdb
    - cloc
    - python-dev
    - python-pip
    - bison
    - flex
    - doxygen

- name: Upgrade pip with pip
  pip:
    name: pip
    state: latest
  sudo: true
