---

- name: Check for Eclipse
  stat:
    path: ~/bin/eclipse
  register: eclipse_directory

- name: Download Eclipse Luna
  get_url:
    url: http://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/luna/SR2/eclipse-java-luna-SR2-linux-gtk-x86_64.tar.gz&r=1
    dest: /tmp/eclipse-luna.tar.gz
  when: not eclipse_directory.stat.exists

- name: Extract Eclipse Luna
  unarchive:
    src: /tmp/eclipse-luna.tar.gz
    dest: ~/bin
    copy: no
  when: not eclipse_directory.stat.exists

- name: Delete the downloaded Eclipse Luna archive
  file:
    path: /tmp/eclipse-luna.tar.gz
    state: absent
  when: not eclipse_directory.stat.exists

- name: Install Maven
  apt:
    pkg: maven
    state: installed
  sudo: true

- name: Test for Java version
  shell: java -version 2>&1 | head -n 1
  register: java_version
  changed_when: java_version.stdout.find('1.8.0_45') == -1

- name: Download, extract, and prepare JDK8 from Oracle
  shell: |
    mkdir -p $JAVA_DIR
    cd $JAVA_DIR
    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/$JDK_VERSION-b$BUILD_NUMBER/jdk-$JDK_VERSION-linux-x64.tar.gz
    tar -zxf jdk-$JDK_VERSION-linux-x64.tar.gz
    rm jdk-$JDK_VERSION-linux-x64.tar.gz

    wget --no-check-certificate --no-cookies --header "Cookie: oraclelicense=accept-securebackup-cookie" "https://edelivery.oracle.com/otn-pub/java/jce/8/jce_policy-8.zip"

    unzip jce_policy-8.zip
    rm jce_policy-8.zip
    mv UnlimitedJCEPolicyJDK8/US_export_policy.jar $JDK_FOLDER/jre/lib/security
    mv UnlimitedJCEPolicyJDK8/local_policy.jar $JDK_FOLDER/jre/lib/security
    rm -rf UnlimitedJCEPolicyJDK8
  environment:
    JDK_VERSION: "8u45"
    JDK_FOLDER: "jdk1.8.0_40"
    BUILD_NUMBER: "14"
    JAVA_DIR: "/tmp/java"
    TARGET_JVM_DIR: "/usr/lib/jvm"
  when: java_version.stdout.find('1.8.0_45') == -1
  register: download_jdk8

- name: Install downloaded JDK8
  shell: |
    mv /tmp/java/jdk1.8.0_45 /usr/lib/jvm/
    rm -rf /usr/lib/jvm/default-java
    ln -s /usr/lib/jvm/jdk1.8.0_45 /usr/lib/jvm/default-java
    update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.8.0_45/bin/java 100
    update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk1.8.0_45/bin/javac 100
    update-alternatives --set java /usr/lib/jvm/jdk1.8.0_45/bin/java
    update-alternatives --set javac /usr/lib/jvm/jdk1.8.0_45/bin/javac
  sudo: true
  when: download_jdk8.changed
