---

- name: Add Docker key to apt
  apt_key:
    keyserver: hkp://p80.pool.sks-keyservers.net
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
  sudo: true

- name: Add Docker repository to apt
  apt_repository:
    repo: deb https://get.docker.com/ubuntu docker main
    state: present
  sudo: true

- name: Install Docker
  apt:
    pkg: lxc-docker
    state: installed
  sudo: true

- name: Add myself to the Docker group
  user:
    name: martin
    groups: docker
    append: yes
  sudo: true

- name: Install Docker Compose
  pip:
    name: docker-compose
    state: installed
  sudo: true
